In [1]:
import numpy as np
array=np.arange(20)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
array1=np.array([1,2,3,4])
print(array1[1])

2


In [9]:
array=np.arange(18).reshape(3,6)
array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [10]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.full([3,3],5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [22]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.linspace(0,10,num=3)

array([ 0.,  5., 10.])

In [25]:
import numpy as np
a=np.arange(10)
a
np.empty_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.full_like(a,4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [31]:
np.asarray(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.geomspace(2,10,5)

array([ 2.        ,  2.99069756,  4.47213595,  6.68740305, 10.        ])

In [33]:
np.copy(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.diag(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [35]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.random.random([2,3])

array([[0.45567303, 0.97768121, 0.11391485],
       [0.98717644, 0.4079732 , 0.92039564]])

In [39]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [41]:
import numpy as np
a=np.array([1,2,3,4])
a[2]

3

In [42]:
print(a[2]+a[3])

7


In [14]:
print(a.dtype)

float64


In [15]:
print(a.dtype)

float64


In [8]:
x=a.view()
a[0]=42
print(a)
print(x)

[42.   2.1  3.1]
[42.   2.1  3.1]


In [13]:
x=a.reshape(3,1)
print(x)

[[42. ]
 [ 2.1]
 [ 3.1]]


In [12]:
print(a.shape)

(3,)


In [21]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
x=np.concatenate((a,b),axis=1)
print(x)

[[1 2 5 6]
 [3 4 7 8]]


In [23]:
x=np.stack((a,b),axis=1)
print(x)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [26]:
import numpy as np
a=np.array([1,2,3,4,5,4,4])
x=np.where(a=4)
print(x)

TypeError: where() got an unexpected keyword argument 'a'

In [27]:
x=np.sort(a)
print(x)

[1 2 3 4 4 4 5]
